### ISSUE TITLE
Cannot rename files with spaces in name

### ISSUE THREAD

**Issue by linuxnutzer** [bitleaf/kde5-dolphin-service-menu-add-timestamp#4]
You have to quote the name with "" like:
mv "%f" "$(pwd)/$(stat -c %y /var/log/ | cut -c1-10)-$(basename %f)"

**Comment by MathiasRenner** [comment]
Processed together with https://github.com/bitleaf/kde5-dolphin-service-menu-add-timestamp/issues/5.
