### ISSUE TITLE
Code enhancements

### ISSUE THREAD

**Issue by linuxnutzer** [bitleaf/kde5-dolphin-service-menu-add-timestamp#5]
To be more flexible with the timestamp you can use gnu date:

mv "%f" "$(pwd)/$(date '+%%F')-$(basename %f)"

and

mv "%f" "$(pwd)/$(date -r %f '+%%F')-$(basename %f)"

Be aware of the double %% in the date format string. It is necessary because %F is a macro from KDE.

Instead of %F you can easily create you own date format. See man date.

**Comment by MathiasRenner** [comment]
Thank you very much! I updated the source code correspondingly.

**Comment by klawdhfzasjhaa** [comment]
I've tried to customize the script to get a format like: Y.m.d. (e.g. 2018.09.16. Testfile). It wasn't clear to me, that the double percent (%%) is needed in front of EVERY format sign. In my case I needed: Exec=mv "%f" "$(pwd)/$(date '+%%Y.%%m.%%d. ')$(basename %f)". Maybe that info is good to have in the README.

**Comment by MathiasRenner** [comment]
@klawdhfzasjhaa Thank you very much for the hint!! I updated section  "Customize date format" in README.
