### ISSUE TITLE
[Feature Request] It is possible to allow format change?

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [bitleaf/kde5-dolphin-service-menu-add-timestamp#6]
I would like to have other separators. Others maybe want to change the order of the time pieces or even add the current time.

**Comment by MathiasRenner** [comment]
Thanks for getting in touch! Basically, the functionality is configured in the line starting with `Exec` in the source code: https://github.com/bitleaf/kde5-dolphin-service-menu-add-timestamp/blob/master/add-timestamp-file-last-modified.desktop#L11

You can change this functionality to whatever you like including changing the seperators. It's basically just (sometimes ugly) bash scripting.
