### ISSUE TITLE
Not installable via Dolphin-Menu

### ISSUE THREAD

**Issue by xstable** [bitleaf/kde5-dolphin-service-menu-add-timestamp#7]
If I try to install your Plugin via Dolpin  ⇒ Add Plugins, I got this Message: 

> Unknown error in API of Open-Collaboration-Service (103).   [Translated this Message form german language]

**Comment by MathiasRenner** [comment]
@xstable Yep, this does not work. I don't know why, and unfortunately will not look into that...
